name: jfrog-upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_URL: https://zabcia.jfrog.io
          JF_USER: ${{ secrets.JF_USER }}
          # JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_PASSWORD }}
      - name: Upload Client binaries to JFrog
        run: 'jf rt u test.zip default-generic-local'
