name: jfrog-upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      URL: https://zabcia.jfrog.io
    steps:
      - uses: actions/checkout@v3
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_URL: ${{ env.URL }}
          JF_USER: ${{ secrets.JF_USER }}
          # JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_PASSWORD }}
      - name: Upload Client binaries to JFrog
        run: 'jf rt upload test.zip default-generic-local'
      - name: Print link
        run: echo $URL/artifactory/default-generic-local/test.zip
